#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Spanish Conjugation Trainer — desktop app (Tkinter)
=======================================================================
Nature-inspired visual theme (khaki green / brown), with a real home
screen offering three centered buttons:
  - 🥾 Conjugation Game: a 60-second timed drill, with a tense filter
    and an "all persons" mode
  - 🌲 Course: a refresher on formation rules, examples, and the most
    common irregular verbs for the present, imperfect, and preterite
  - 🗣️ Translation: translate sentences generated by the app

Run with:  python3 spanish_conjugation_app.py
(Tkinter ships with the standard Python installation)

Note: the "nature" visuals are represented with emoji (🏔️ 🌲 🪨 🫐 🏞️ …)
rather than image files, so this script stays a single, portable Python
file with no external image dependencies.
"""

import tkinter as tk
from tkinter import ttk, messagebox
import random
import re
import sys
import os
import unicodedata


def resource_path(relative_path):
    """Return the path to a bundled resource, whether the script runs
    directly or packaged as an executable (PyInstaller)."""
    base_path = getattr(sys, "_MEIPASS", os.path.dirname(os.path.abspath(__file__)))
    return os.path.join(base_path, relative_path)


# ---------------------------------------------------------------------------
# Conjugation data (used by the game and the translation exercise)
# ---------------------------------------------------------------------------

PRONOUNS = ["yo", "tú", "él/ella/Ud.", "nosotros", "vosotros", "ellos/Uds."]
TENSES = ["present", "imperfect", "preterite"]

REGULAR_VERBS = [
    "hablar", "estudiar", "trabajar", "viajar", "comprar", "cantar", "bailar", "caminar",
    "comer", "aprender", "vender", "deber", "correr",
    "vivir", "escribir", "abrir", "decidir", "asistir",
]

IRREGULAR_VERBS = {
    "ser": {
        "present": ["soy", "eres", "es", "somos", "sois", "son"],
        "imperfect": ["era", "eras", "era", "éramos", "erais", "eran"],
        "preterite": ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    },
    "estar": {
        "present": ["estoy", "estás", "está", "estamos", "estáis", "están"],
        "preterite": ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"],
    },
    "tener": {
        "present": ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"],
        "preterite": ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"],
    },
    "ir": {
        "present": ["voy", "vas", "va", "vamos", "vais", "van"],
        "imperfect": ["iba", "ibas", "iba", "íbamos", "ibais", "iban"],
        "preterite": ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"],
    },
    "hacer": {
        "present": ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"],
        "preterite": ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"],
    },
    "poder": {
        "present": ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"],
        "preterite": ["pude", "pudiste", "pudo", "pudimos", "pudisteis", "pudieron"],
    },
    "querer": {
        "present": ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"],
        "preterite": ["quise", "quisiste", "quiso", "quisimos", "quisisteis", "quisieron"],
    },
    "decir": {
        "present": ["digo", "dices", "dice", "decimos", "decís", "dicen"],
        "preterite": ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"],
    },
    "venir": {
        "present": ["vengo", "vienes", "viene", "venimos", "venís", "vienen"],
        "preterite": ["vine", "viniste", "vino", "vinimos", "vinisteis", "vinieron"],
    },
    "saber": {
        "present": ["sé", "sabes", "sabe", "sabemos", "sabéis", "saben"],
        "preterite": ["supe", "supiste", "supo", "supimos", "supisteis", "supieron"],
    },
    "ver": {
        "imperfect": ["veía", "veías", "veía", "veíamos", "veíais", "veían"],
        "preterite": ["vi", "viste", "vio", "vimos", "visteis", "vieron"],
    },
    "poner": {
        "preterite": ["puse", "pusiste", "puso", "pusimos", "pusisteis", "pusieron"],
    },
    "traer": {
        "preterite": ["traje", "trajiste", "trajo", "trajimos", "trajisteis", "trajeron"],
    },
    "dar": {
        "preterite": ["di", "diste", "dio", "dimos", "disteis", "dieron"],
    },
}

ALL_VERBS = REGULAR_VERBS + list(IRREGULAR_VERBS.keys())

REGULAR_ENDINGS = {
    "present": {
        "ar": ["o", "as", "a", "amos", "áis", "an"],
        "er": ["o", "es", "e", "emos", "éis", "en"],
        "ir": ["o", "es", "e", "imos", "ís", "en"],
    },
    "imperfect": {
        "ar": ["aba", "abas", "aba", "ábamos", "abais", "aban"],
        "er": ["ía", "ías", "ía", "íamos", "íais", "ían"],
        "ir": ["ía", "ías", "ía", "íamos", "íais", "ían"],
    },
    "preterite": {
        "ar": ["é", "aste", "ó", "amos", "asteis", "aron"],
        "er": ["í", "iste", "ió", "imos", "isteis", "ieron"],
        "ir": ["í", "iste", "ió", "imos", "isteis", "ieron"],
    },
}

# ---------------------------------------------------------------------------
# Art direction: nature theme — khaki green & brown
# ---------------------------------------------------------------------------

FONT_FAMILY = "Comic Sans MS"

BG_APP = "#F3ECD9"        # light sand / parchment
BG_CARD = "#FFFDF7"       # cream card, almost white
BG_SETTINGS = "#E8E1C8"   # very light khaki settings bar
BORDER_SETTINGS = "#C9BE9A"

COL_TEXT = "#3B2F27"      # dark brown (main text)
COL_MUTED = "#7A6A55"     # brown-grey (secondary text)
COL_OK = "#4C7A3D"        # forest green (correct answer)
COL_KO = "#A0522D"        # terracotta (wrong answer)
COL_STREAK = "#B8860B"    # gold/honey (streak)
COL_ACCENT = "#A0522D"    # rust (hard mode active, tip boxes)

COL_KAKI = "#7D8F5A"          # main khaki green (present)
COL_KAKI_DARK = "#4B5D2A"     # dark olive green (titles, menu buttons)
COL_BROWN = "#8B5E3C"         # medium brown (imperfect)
COL_BROWN_DARK = "#4B3621"    # dark brown (preterite, titles)
COL_MOSS = "#5C6B3C"          # dark moss green (translation tab)

TENSE_COLORS = {
    "present": COL_KAKI,
    "imperfect": COL_BROWN,
    "preterite": COL_BROWN_DARK,
}
TENSE_EMOJI = {
    "present": "🌲",
    "imperfect": "🏞️",
    "preterite": "🪨",
}
TENSE_SUBTITLES = {
    "present": "Presente de indicativo",
    "imperfect": "Pretérito imperfecto",
    "preterite": "Pretérito indefinido",
}

TRANSLATION_COLOR = COL_MOSS
TRANSLATION_EMOJI = "🗣️"

DURATION_QUESTION = 60  # seconds

CORRECT_MESSAGES = [
    "Excellent! 🎉", "Great job! 🙌", "Perfect! ✨", "Awesome! 💪",
    "Well done! 👏", "Nailed it! 🌟", "Fantastic! 🚀",
]
WRONG_MESSAGES = [
    "Not quite... 🤔", "So close! 😅", "Let's try again! 💡", "That happens! 🌱",
]
TIMEOUT_MESSAGES = [
    "Too slow this time! ⏰", "Time flew by! ⌛", "Next one's yours! 🕒",
]

# ---------------------------------------------------------------------------
# Course content (English explanations of Spanish grammar)
# ---------------------------------------------------------------------------

COURSE_DATA = {
    "present": {
        "intro": (
            "Drop the infinitive ending (-AR, -ER, -IR) and add the "
            "following endings:"
        ),
        "groups": {
            "-AR (hablar)": ["habl-o", "habl-as", "habl-a", "habl-amos", "habl-áis", "habl-an"],
            "-ER (comer)": ["com-o", "com-es", "com-e", "com-emos", "com-éis", "com-en"],
            "-IR (vivir)": ["viv-o", "viv-es", "viv-e", "viv-imos", "viv-ís", "viv-en"],
        },
        "examples": [
            ("Yo hablo español todos los días.", "I speak Spanish every day."),
            ("¿Tú comes carne o eres vegetariano?", "Do you eat meat, or are you vegetarian?"),
            ("Nosotros vivimos en Madrid desde 2020.", "We've lived in Madrid since 2020."),
        ],
        "tip": (
            "Tip: in the present tense, only the « nosotros/vosotros » form always "
            "keeps the infinitive's vowel (-amos/-áis, -emos/-éis, -imos/-ís) — a "
            "handy way to spot the verb group."
        ),
        "irregulars": [
            ("ser (to be)", ["soy", "eres", "es", "somos", "sois", "son"]),
            ("estar (to be / state)", ["estoy", "estás", "está", "estamos", "estáis", "están"]),
            ("tener (to have)", ["tengo", "tienes", "tiene", "tenemos", "tenéis", "tienen"]),
            ("ir (to go)", ["voy", "vas", "va", "vamos", "vais", "van"]),
            ("hacer (to do/make)", ["hago", "haces", "hace", "hacemos", "hacéis", "hacen"]),
            ("poder (to be able to)", ["puedo", "puedes", "puede", "podemos", "podéis", "pueden"]),
            ("querer (to want)", ["quiero", "quieres", "quiere", "queremos", "queréis", "quieren"]),
            ("decir (to say/tell)", ["digo", "dices", "dice", "decimos", "decís", "dicen"]),
            ("venir (to come)", ["vengo", "vienes", "viene", "venimos", "venís", "vienen"]),
            ("saber (to know)", ["sé", "sabes", "sabe", "sabemos", "sabéis", "saben"]),
        ],
        "irregular_note": (
            "These verbs show frequent irregularities: stem changes (e→ie, o→ue), "
            "an irregular 1st-person form (tengo, hago, digo, sé), or a fully "
            "irregular conjugation (ser, ir)."
        ),
        "extra_tip": (
            "💡 Extra tip: the structure « ir a + infinitive » (voy a comer) "
            "expresses the near future, just like « going to + infinitive » in "
            "English."
        ),
    },
    "imperfect": {
        "intro": (
            "The imperfect (« pretérito imperfecto ») describes habitual or "
            "ongoing actions in the past, with no precise end point (similar to "
            "English 'used to' or the past continuous)."
        ),
        "groups": {
            "-AR (hablar)": ["habl-aba", "habl-abas", "habl-aba", "habl-ábamos", "habl-abais", "habl-aban"],
            "-ER (comer)": ["com-ía", "com-ías", "com-ía", "com-íamos", "com-íais", "com-ían"],
            "-IR (vivir)": ["viv-ía", "viv-ías", "viv-ía", "viv-íamos", "viv-íais", "viv-ían"],
        },
        "examples": [
            ("Cuando era niño, jugaba en el parque cada tarde.",
             "When I was a kid, I used to play in the park every afternoon."),
            ("Mis padres vivían en Barcelona en los años 90.",
             "My parents used to live in Barcelona in the 90s."),
            ("Nosotros comíamos juntos todos los domingos.",
             "We used to eat together every Sunday."),
        ],
        "tip": (
            "Good to know: the Spanish imperfect is the most regular tense of "
            "all — only three verbs are irregular in the entire language!"
        ),
        "irregulars": [
            ("ser (to be)", ["era", "eras", "era", "éramos", "erais", "eran"]),
            ("ir (to go)", ["iba", "ibas", "iba", "íbamos", "ibais", "iban"]),
            ("ver (to see)", ["veía", "veías", "veía", "veíamos", "veíais", "veían"]),
        ],
        "irregular_note": (
            "Every other verb, including those irregular in the present (tener, "
            "hacer, poder…), is perfectly regular in the imperfect."
        ),
        "extra_tip": (
            "💡 Extra tip: the Spanish imperfect is used almost exactly like "
            "English 'used to' or the past continuous — to describe, express a "
            "past habit, or an ongoing past action."
        ),
    },
    "preterite": {
        "intro": (
            "The preterite (« pretérito indefinido ») expresses a single, "
            "completed action in the past (roughly equivalent to the English "
            "simple past)."
        ),
        "groups": {
            "-AR (hablar)": ["habl-é", "habl-aste", "habl-ó", "habl-amos", "habl-asteis", "habl-aron"],
            "-ER (comer)": ["com-í", "com-iste", "com-ió", "com-imos", "com-isteis", "com-ieron"],
            "-IR (vivir)": ["viv-í", "viv-iste", "viv-ió", "viv-imos", "viv-isteis", "viv-ieron"],
        },
        "examples": [
            ("Ayer hablé con mi jefe sobre el proyecto.", "Yesterday I talked to my boss about the project."),
            ("Ella vivió dos años en Argentina.", "She lived in Argentina for two years."),
            ("El año pasado fuimos de vacaciones a México.",
             "Last year we went on vacation to Mexico."),
        ],
        "tip": (
            "Watch out: this is the tense with the most irregularities in "
            "Spanish — many very common verbs change their stem (tuve, hice, "
            "dije…)."
        ),
        "irregulars": [
            ("ser / ir", ["fui", "fuiste", "fue", "fuimos", "fuisteis", "fueron"]),
            ("estar (to be)", ["estuve", "estuviste", "estuvo", "estuvimos", "estuvisteis", "estuvieron"]),
            ("tener (to have)", ["tuve", "tuviste", "tuvo", "tuvimos", "tuvisteis", "tuvieron"]),
            ("hacer (to do/make)", ["hice", "hiciste", "hizo", "hicimos", "hicisteis", "hicieron"]),
            ("poder (to be able to)", ["pude", "pudiste", "pudo", "pudimos", "pudisteis", "pudieron"]),
            ("poner (to put)", ["puse", "pusiste", "puso", "pusimos", "pusisteis", "pusieron"]),
            ("querer (to want)", ["quise", "quisiste", "quiso", "quisimos", "quisisteis", "quisieron"]),
            ("venir (to come)", ["vine", "viniste", "vino", "vinimos", "vinisteis", "vinieron"]),
            ("decir (to say/tell)", ["dije", "dijiste", "dijo", "dijimos", "dijisteis", "dijeron"]),
            ("traer (to bring)", ["traje", "trajiste", "trajo", "trajimos", "trajisteis", "trajeron"]),
            ("dar (to give)", ["di", "diste", "dio", "dimos", "disteis", "dieron"]),
            ("saber (to know)", ["supe", "supiste", "supo", "supimos", "supisteis", "supieron"]),
        ],
        "irregular_note": (
            "Note: « ser » and « ir » share the exact same conjugation in the "
            "preterite — only context tells them apart (fui = 'I was' or 'I "
            "went')."
        ),
        "extra_tip": (
            "💡 Extra tip: in Spain, people often use « he hablado » (present "
            "perfect) for a recent action, and the preterite for something more "
            "distant or fully finished. In Latin America, the preterite is "
            "largely preferred in both cases."
        ),
    },
}

# ---------------------------------------------------------------------------
# Sentence bank for the Translation tab (English -> Spanish)
# ---------------------------------------------------------------------------

TRANSLATION_SENTENCES = {
    "present": [
        ("I speak Spanish every day.", "Yo hablo español todos los días."),
        ("You eat too fast.", "Tú comes demasiado rápido."),
        ("She lives in Seville.", "Ella vive en Sevilla."),
        ("We have two cars.", "Nosotros tenemos dos coches."),
        ("They go to the movies on Saturdays.", "Ellos van al cine los sábados."),
        ("You (plural) do homework together.", "Vosotros hacéis los deberes juntos."),
        ("I am a Spanish student.", "Yo soy estudiante de español."),
        ("She wants a coffee.", "Ella quiere un café."),
        ("We have lived in Madrid since 2020.", "Nosotros vivimos en Madrid desde 2020."),
        ("Can you help me, please?", "¿Tú puedes ayudarme, por favor?"),
    ],
    "imperfect": [
        ("When I was a child, I used to play in the park.", "Cuando era niño, jugaba en el parque."),
        ("My parents used to live in Barcelona.", "Mis padres vivían en Barcelona."),
        ("We used to eat together on Sundays.", "Nosotros comíamos juntos los domingos."),
        ("You used to talk a lot with your grandparents.", "Tú hablabas mucho con tus abuelos."),
        ("She used to go to the beach every summer.", "Ella iba a la playa cada verano."),
        ("You (plural) used to watch TV after dinner.", "Vosotros veíais la tele después de cenar."),
        ("I had a dog when I was little.", "Yo tenía un perro cuando era niño."),
        ("They were very tired.", "Ellos estaban muy cansados."),
        ("We used to study Spanish in high school.", "Nosotros estudiábamos español en el instituto."),
        ("She used to work in Madrid before.", "Ella trabajaba en Madrid antes."),
    ],
    "preterite": [
        ("Yesterday, I talked to my boss.", "Ayer hablé con mi jefe."),
        ("She had an accident last month.", "Ella tuvo un accidente el mes pasado."),
        ("We went to Barcelona in 2019.", "Nosotros fuimos a Barcelona en 2019."),
        ("You made dinner last night.", "Tú hiciste la cena anoche."),
        ("They came to the party on Saturday.", "Ellos vinieron a la fiesta el sábado."),
        ("You (plural) told the truth.", "Vosotros dijisteis la verdad."),
        ("I saw that movie last year.", "Yo vi esa película el año pasado."),
        ("She managed to finish the project on time.", "Ella pudo terminar el proyecto a tiempo."),
        ("We had a nice surprise.", "Nosotros tuvimos una buena sorpresa."),
        ("He put the book on the table.", "Él puso el libro en la mesa."),
    ],
}


def regular_conjugation(verb, tense):
    group = verb[-2:]
    stem = verb[:-2]
    return [stem + ending for ending in REGULAR_ENDINGS[tense][group]]


def get_conjugation(verb, tense):
    if verb in IRREGULAR_VERBS and tense in IRREGULAR_VERBS[verb]:
        return IRREGULAR_VERBS[verb][tense]
    return regular_conjugation(verb, tense)


def normalize(text):
    text = text.strip().lower()
    text = unicodedata.normalize("NFKD", text)
    return "".join(c for c in text if not unicodedata.combining(c))


def normalize_sentence(text):
    """Lenient comparison for full sentences: accents, case, punctuation
    and repeated spaces are all ignored."""
    text = normalize(text)
    text = re.sub(r"[¿¡?!.,;:]", "", text)
    text = re.sub(r"\s+", " ", text).strip()
    return text


# ---------------------------------------------------------------------------
# GUI application
# ---------------------------------------------------------------------------

class SpanishConjugationApp(tk.Tk):
    def __init__(self):
        super().__init__()
        self.title("🇪🇸 Spanish Conjugation Trainer")
        self.geometry("880x860")
        self.minsize(820, 800)
        self.configure(bg=BG_APP)
        self._set_app_icon()

        # Game state
        self.score = 0
        self.total = 0
        self.streak = 0
        self.best_streak = 0
        self.time_left = DURATION_QUESTION
        self.timer_id = None
        self.reviewing_answer = False
        self.all_persons_mode = False
        self.entries = []
        self.feedback_labels = []
        self.verb = None
        self.tense = None
        self.pronoun_idx = None
        self.correct_answer = None
        self.current_page = None

        # Translation tab state
        self.score_translation = 0
        self.total_translation = 0
        self.translation_reviewing = False
        self.translation_sentence_en = None
        self.translation_sentence_es = None
        self.translation_tense = None

        self._setup_styles()
        self._build_pages()

        self.bind("<Return>", lambda e: self._on_enter())
        self.protocol("WM_DELETE_WINDOW", self.quit_app)

        self._show_page(self.menu_frame)

    # ------------------------------------------------------------------
    # Application icon
    # ------------------------------------------------------------------

    def _set_app_icon(self):
        ico_path = resource_path(os.path.join("assets", "icon.ico"))
        png_path = resource_path(os.path.join("assets", "icon.png"))
        try:
            if os.path.exists(ico_path):
                self.iconbitmap(ico_path)
                return
        except tk.TclError:
            pass
        try:
            if os.path.exists(png_path):
                self._icon_img = tk.PhotoImage(file=png_path)
                self.iconphoto(True, self._icon_img)
        except tk.TclError:
            pass

    # ------------------------------------------------------------------
    # Styles
    # ------------------------------------------------------------------

    def _setup_styles(self):
        style = ttk.Style(self)
        try:
            style.theme_use("clam")
        except tk.TclError:
            pass

        style.configure(
            "TEntry", font=(FONT_FAMILY, 16), padding=6,
            fieldbackground="#FFFDF7", bordercolor=BORDER_SETTINGS
        )
        style.configure("TSpinbox", font=(FONT_FAMILY, 12), padding=4)

        style.configure(
            "Quit.TButton", font=(FONT_FAMILY, 13, "bold"),
            padding=(14, 10), background="#D8CDA9", foreground=COL_TEXT
        )
        style.map("Quit.TButton", background=[("active", "#C9BE9A")])

        for tense, color in TENSE_COLORS.items():
            style_name = f"{tense}.TButton"
            style.configure(
                style_name, font=(FONT_FAMILY, 15, "bold"),
                padding=(18, 12), background=color, foreground="white", borderwidth=0
            )
            style.map(style_name, background=[("active", color)])

        style.configure(
            "translation.TButton", font=(FONT_FAMILY, 15, "bold"),
            padding=(18, 12), background=TRANSLATION_COLOR, foreground="white", borderwidth=0
        )
        style.map("translation.TButton", background=[("active", TRANSLATION_COLOR)])

    # ------------------------------------------------------------------
    # Page construction (home / game / course / translation), stacked
    # ------------------------------------------------------------------

    def _build_pages(self):
        container = tk.Frame(self, bg=BG_APP)
        container.pack(fill="both", expand=True)
        container.grid_rowconfigure(0, weight=1)
        container.grid_columnconfigure(0, weight=1)

        self.menu_frame = tk.Frame(container, bg=BG_APP)
        self.game_frame = tk.Frame(container, bg=BG_APP)
        self.course_frame = tk.Frame(container, bg=BG_APP)
        self.translation_frame = tk.Frame(container, bg=BG_APP)

        for frame in (self.menu_frame, self.game_frame, self.course_frame, self.translation_frame):
            frame.grid(row=0, column=0, sticky="nsew")

        self._build_menu(self.menu_frame)
        self._build_game_page(self.game_frame)
        self._build_course_page(self.course_frame)
        self._build_translation_page(self.translation_frame)

    def _show_page(self, frame):
        if frame is not self.game_frame:
            self._stop_timer()
        self.current_page = frame
        frame.tkraise()

    # ==================================================================
    # HOME MENU
    # ==================================================================

    def _build_menu(self, parent):
        tk.Label(
            parent, text="🏔️   🌲   🪨   🫐   🏞️", font=(FONT_FAMILY, 30),
            bg=BG_APP, fg=COL_KAKI_DARK
        ).pack(pady=(56, 10))

        tk.Label(
            parent, text="🇪🇸 Spanish Conjugation Trainer",
            font=(FONT_FAMILY, 27, "bold"), bg=BG_APP, fg=COL_BROWN_DARK,
            justify="center"
        ).pack(pady=(0, 8))

        tk.Label(
            parent,
            text="Set off on an adventure through the Spanish tenses,\nlike a hike through nature.",
            font=(FONT_FAMILY, 13, "italic"), bg=BG_APP, fg=COL_MUTED, justify="center"
        ).pack(pady=(0, 50))

        cards = tk.Frame(parent, bg=BG_APP)
        cards.pack()

        self._build_menu_card(
            cards, emoji="🥾", title="Conjugation Game",
            subtitle="Race the clock (60s)\nand level up tense by tense.",
            color=COL_KAKI_DARK, command=lambda: self._go_to_game()
        ).grid(row=0, column=0, padx=16, pady=10)

        self._build_menu_card(
            cards, emoji="🌲", title="Course",
            subtitle="Review the formation rules,\nexamples, and irregular verbs.",
            color=COL_BROWN, command=self._go_to_course
        ).grid(row=0, column=1, padx=16, pady=10)

        self._build_menu_card(
            cards, emoji="🗣️", title="Translation",
            subtitle="Translate sentences generated\nby the app, tense by tense.",
            color=TRANSLATION_COLOR, command=self._go_to_translation
        ).grid(row=0, column=2, padx=16, pady=10)

        tk.Label(
            parent, text="🍃  You can always come back here via « 🏠 Menu »  🍃",
            font=(FONT_FAMILY, 10, "italic"), bg=BG_APP, fg=COL_MUTED
        ).pack(pady=30)

    def _build_menu_card(self, parent, emoji, title, subtitle, color, command):
        card = tk.Frame(
            parent, bg=color, width=235, height=225,
            highlightbackground=COL_BROWN_DARK, highlightthickness=2
        )
        card.pack_propagate(False)

        icon = tk.Label(card, text=emoji, font=(FONT_FAMILY, 36), bg=color)
        icon.pack(pady=(24, 6))
        title_lbl = tk.Label(card, text=title, font=(FONT_FAMILY, 15, "bold"), bg=color, fg="white")
        title_lbl.pack()
        subtitle_lbl = tk.Label(
            card, text=subtitle, font=(FONT_FAMILY, 9), bg=color, fg="#F3ECD9", justify="center"
        )
        subtitle_lbl.pack(pady=(8, 0))

        for widget in (card, icon, title_lbl, subtitle_lbl):
            widget.configure(cursor="hand2")
            widget.bind("<Button-1>", lambda e: command())

        return card

    def _go_to_game(self, tense_filter=None):
        if tense_filter is not None:
            self._set_tense_filter(tense_filter)
        self._show_page(self.game_frame)
        self.new_question()

    def _go_to_course(self):
        self._show_page(self.course_frame)

    def _go_to_translation(self):
        self._show_page(self.translation_frame)
        self.new_sentence()

    def _go_to_menu(self):
        self._show_page(self.menu_frame)

    # ==================================================================
    # PAGE: CONJUGATION GAME
    # ==================================================================

    def _build_game_page(self, parent):
        topbar = tk.Frame(parent, bg=BG_APP)
        topbar.pack(fill="x")
        tk.Button(
            topbar, text="🏠 Menu", font=(FONT_FAMILY, 11, "bold"),
            bg="#D8CDA9", fg=COL_TEXT, relief="flat", bd=0, padx=12, pady=6,
            cursor="hand2", command=self._go_to_menu
        ).pack(side="left", padx=16, pady=10)

        self._build_header(parent)
        self._build_settings_bar(parent)
        self._build_score_bar(parent)
        self._build_question_area(parent)
        self._build_footer(parent)

    def _build_header(self, parent):
        self.header_frame = tk.Frame(parent, bg=TENSE_COLORS["present"], height=120)
        self.header_frame.pack(fill="x")
        self.header_frame.pack_propagate(False)

        left = tk.Frame(self.header_frame, bg=TENSE_COLORS["present"])
        left.pack(side="left", padx=24, pady=16, anchor="w")

        self.title_label = tk.Label(
            left, text="🌲 PRESENT", font=(FONT_FAMILY, 28, "bold"),
            fg="white", bg=TENSE_COLORS["present"]
        )
        self.title_label.pack(anchor="w")

        self.subtitle_label = tk.Label(
            left, text="Presente de indicativo", font=(FONT_FAMILY, 13, "italic"),
            fg="white", bg=TENSE_COLORS["present"]
        )
        self.subtitle_label.pack(anchor="w")

        right = tk.Frame(self.header_frame, bg=TENSE_COLORS["present"])
        right.pack(side="right", padx=24, pady=16, anchor="e")

        tk.Label(right, text="⏱", font=(FONT_FAMILY, 30), fg="white",
                 bg=TENSE_COLORS["present"]).pack(side="left")
        self.timer_label = tk.Label(
            right, text=f"{DURATION_QUESTION}s", font=(FONT_FAMILY, 32, "bold"),
            fg="white", bg=TENSE_COLORS["present"]
        )
        self.timer_label.pack(side="left", padx=(6, 0))

    def _build_settings_bar(self, parent):
        outer = tk.Frame(parent, bg=BG_SETTINGS, highlightbackground=BORDER_SETTINGS, highlightthickness=1)
        outer.pack(fill="x", padx=20, pady=(14, 0))

        row1 = tk.Frame(outer, bg=BG_SETTINGS)
        row1.pack(fill="x", padx=10, pady=(10, 4))

        tk.Label(
            row1, text="📚 Tense to practice:",
            font=(FONT_FAMILY, 12, "bold"), bg=BG_SETTINGS, fg=COL_BROWN_DARK
        ).pack(side="left", padx=(0, 10))

        self.tense_filter = None  # None = all tenses (random)
        self.tense_buttons = {}
        tense_choices = [("🔀 All tenses", None)] + [
            (f"{TENSE_EMOJI[t]} {t.capitalize()}", t) for t in TENSES
        ]
        for label, value in tense_choices:
            btn = tk.Button(
                row1, text=label, font=(FONT_FAMILY, 11, "bold"),
                relief="flat", bd=0, padx=10, pady=6, cursor="hand2",
                command=lambda v=value: self._set_tense_filter(v)
            )
            btn.pack(side="left", padx=4)
            self.tense_buttons[value] = btn

        row2 = tk.Frame(outer, bg=BG_SETTINGS)
        row2.pack(fill="x", padx=10, pady=(4, 10))

        tk.Label(
            row2, text="🌾 Hard mode:",
            font=(FONT_FAMILY, 12, "bold"), bg=BG_SETTINGS, fg=COL_BROWN_DARK
        ).pack(side="left", padx=(0, 10))

        self.all_persons_on = False
        self.all_persons_btn = tk.Button(
            row2, font=(FONT_FAMILY, 11, "bold"), relief="flat", bd=0,
            padx=10, pady=6, cursor="hand2", command=self._toggle_all_persons
        )
        self.all_persons_btn.pack(side="left", padx=4)

        self._refresh_tense_buttons()
        self._refresh_all_persons_button()

    def _set_tense_filter(self, value):
        self.tense_filter = value
        self._refresh_tense_buttons()

    def _refresh_tense_buttons(self):
        for value, btn in self.tense_buttons.items():
            active = value == self.tense_filter
            color = TENSE_COLORS[value] if value else COL_BROWN_DARK
            if active:
                btn.config(bg=color, fg="white")
            else:
                btn.config(bg="#FFFFFF", fg=COL_BROWN_DARK)

    def _toggle_all_persons(self):
        self.all_persons_on = not self.all_persons_on
        self._refresh_all_persons_button()

    def _refresh_all_persons_button(self):
        if self.all_persons_on:
            self.all_persons_btn.config(
                text="🌾 All persons: ON", bg=COL_ACCENT, fg="white"
            )
        else:
            self.all_persons_btn.config(
                text="🌾 All persons: OFF", bg="#FFFFFF", fg=COL_BROWN_DARK
            )

    def _build_score_bar(self, parent):
        bar = tk.Frame(parent, bg=BG_APP)
        bar.pack(fill="x", padx=20, pady=(10, 6))

        self.score_label = tk.Label(
            bar, text="🏆 Score: 0/0", font=(FONT_FAMILY, 15, "bold"),
            bg=BG_APP, fg=COL_TEXT
        )
        self.score_label.pack(side="left")

        self.streak_label = tk.Label(
            bar, text="", font=(FONT_FAMILY, 15, "bold"),
            bg=BG_APP, fg=COL_STREAK
        )
        self.streak_label.pack(side="right")

    def _build_question_area(self, parent):
        outer = tk.Frame(parent, bg=BG_APP)
        outer.pack(fill="both", expand=True, padx=20, pady=10)

        self.question_frame = tk.Frame(
            outer, bg=BG_CARD, highlightbackground=TENSE_COLORS["present"], highlightthickness=3
        )
        self.question_frame.pack(fill="both", expand=True)

        self.result_label = tk.Label(
            parent, text="", font=(FONT_FAMILY, 15, "bold"), bg=BG_APP,
            wraplength=680, justify="left"
        )
        self.result_label.pack(fill="x", padx=24, pady=(0, 6))

    def _build_footer(self, parent):
        footer = tk.Frame(parent, bg=BG_APP)
        footer.pack(fill="x", padx=20, pady=16)

        self.quit_btn = ttk.Button(
            footer, text="🚪 Quit", style="Quit.TButton", command=self.quit_app
        )
        self.quit_btn.pack(side="left")

        self.submit_btn = ttk.Button(
            footer, text="✅ Submit  (Enter)", style="present.TButton", command=self._on_enter
        )
        self.submit_btn.pack(side="right")

    # ------------------------------------------------------------------
    # Question cycle
    # ------------------------------------------------------------------

    def new_question(self):
        self._stop_timer()
        self.reviewing_answer = False
        self.result_label.config(text="")

        self.verb = random.choice(ALL_VERBS)
        self.tense = self.tense_filter if self.tense_filter is not None else random.choice(TENSES)

        self.all_persons_mode = self.all_persons_on

        conjugations = get_conjugation(self.verb, self.tense)
        if self.all_persons_mode:
            self.correct_answer = conjugations
            self.pronoun_idx = None
        else:
            self.pronoun_idx = random.randint(0, 5)
            self.correct_answer = conjugations[self.pronoun_idx]

        self._update_header()
        self._render_question()
        self._start_timer()

    def _update_header(self):
        color = TENSE_COLORS[self.tense]
        emoji = TENSE_EMOJI[self.tense]
        self.header_frame.config(bg=color)
        for child in self.header_frame.winfo_children():
            child.config(bg=color)
            for sub in child.winfo_children():
                sub.config(bg=color)
        self.title_label.config(text=f"{emoji} {self.tense.upper()}")
        self.subtitle_label.config(text=TENSE_SUBTITLES[self.tense])
        self.question_frame.config(highlightbackground=color)
        self.submit_btn.config(style=f"{self.tense}.TButton")

    def _render_question(self):
        for w in self.question_frame.winfo_children():
            w.destroy()
        self.entries = []
        self.feedback_labels = []

        tk.Label(
            self.question_frame, text=f"📝 Verb: {self.verb}",
            font=(FONT_FAMILY, 22, "bold"), bg=BG_CARD, fg=COL_TEXT
        ).pack(pady=(26, 6))

        if self.all_persons_mode:
            tk.Label(
                self.question_frame,
                text="🌾 Conjugate the verb for ALL persons:",
                font=(FONT_FAMILY, 13, "italic"), bg=BG_CARD, fg=COL_ACCENT
            ).pack(pady=(0, 16))

            grid = tk.Frame(self.question_frame, bg=BG_CARD)
            grid.pack(pady=4)

            for i, pronoun in enumerate(PRONOUNS):
                tk.Label(
                    grid, text=pronoun, font=(FONT_FAMILY, 13, "bold"),
                    bg=BG_CARD, fg=COL_MUTED, width=13, anchor="e"
                ).grid(row=i, column=0, padx=(0, 10), pady=6, sticky="e")

                entry = ttk.Entry(grid, font=(FONT_FAMILY, 14), width=18)
                entry.grid(row=i, column=1, pady=6, sticky="w")
                self.entries.append(entry)

                fb = tk.Label(grid, text="", font=(FONT_FAMILY, 13, "bold"), bg=BG_CARD)
                fb.grid(row=i, column=2, padx=(12, 0), pady=6, sticky="w")
                self.feedback_labels.append(fb)

            self.entries[0].focus_set()
        else:
            tk.Label(
                self.question_frame, text=f"👉 Conjugate for: « {PRONOUNS[self.pronoun_idx]} »",
                font=(FONT_FAMILY, 17), bg=BG_CARD, fg=COL_MUTED
            ).pack(pady=(0, 20))

            entry = ttk.Entry(self.question_frame, font=(FONT_FAMILY, 20), width=22, justify="center")
            entry.pack(pady=6, ipady=6)
            entry.focus_set()
            self.entries.append(entry)

    # ------------------------------------------------------------------
    # Timer
    # ------------------------------------------------------------------

    def _start_timer(self):
        self.time_left = DURATION_QUESTION
        self._update_timer_label()
        self._tick()

    def _tick(self):
        if self.time_left <= 0:
            self._on_timeout()
            return
        self._update_timer_label()
        self.time_left -= 1
        self.timer_id = self.after(1000, self._tick)

    def _update_timer_label(self):
        self.timer_label.config(text=f"{self.time_left}s")
        self.timer_label.config(fg="#F3C6B0" if self.time_left <= 10 else "white")

    def _stop_timer(self):
        if self.timer_id is not None:
            self.after_cancel(self.timer_id)
            self.timer_id = None

    def _on_timeout(self):
        self._stop_timer()
        self._grade(timeout=True)

    # ------------------------------------------------------------------
    # Answer submission / grading
    # ------------------------------------------------------------------

    def _on_enter(self):
        if self.current_page is self.game_frame:
            if self.reviewing_answer:
                self.new_question()
            else:
                self._stop_timer()
                self._grade(timeout=False)
        elif self.current_page is self.translation_frame:
            if self.translation_reviewing:
                self.new_sentence()
            else:
                self._grade_translation()

    def _grade(self, timeout):
        self.reviewing_answer = True
        self.total += 1

        if self.all_persons_mode:
            nb_correct = 0
            for i, entry in enumerate(self.entries):
                value = "" if timeout else entry.get()
                correct = self.correct_answer[i]
                ok = normalize(value) == normalize(correct)
                entry.config(state="disabled")
                if ok:
                    nb_correct += 1
                    self.feedback_labels[i].config(text=f"✅ {correct}", fg=COL_OK)
                else:
                    self.feedback_labels[i].config(text=f"❌ {correct}", fg=COL_KO)

            perfect = nb_correct == 6
            if perfect:
                self.score += 1
                self.streak += 1
                self.best_streak = max(self.best_streak, self.streak)
                msg = random.choice(CORRECT_MESSAGES)
                self.result_label.config(text=f"{msg} All 6 forms are correct!", fg=COL_OK)
            else:
                self.streak = 0
                msg = random.choice(TIMEOUT_MESSAGES if timeout else WRONG_MESSAGES)
                self.result_label.config(text=f"{msg} ({nb_correct}/6 forms correct)", fg=COL_KO)
        else:
            entry = self.entries[0]
            value = "" if timeout else entry.get()
            ok = normalize(value) == normalize(self.correct_answer)
            entry.config(state="disabled")
            if ok:
                self.score += 1
                self.streak += 1
                self.best_streak = max(self.best_streak, self.streak)
                msg = random.choice(CORRECT_MESSAGES)
                self.result_label.config(text=msg, fg=COL_OK)
            else:
                self.streak = 0
                msg = random.choice(TIMEOUT_MESSAGES if timeout else WRONG_MESSAGES)
                self.result_label.config(
                    text=f"{msg} The correct answer was: {self.correct_answer}", fg=COL_KO
                )

        self.score_label.config(text=f"🏆 Score: {self.score}/{self.total}")
        self.streak_label.config(text=f"🔥 Streak: {self.streak}" if self.streak >= 2 else "")
        self.submit_btn.config(text="▶ Next question  (Enter)")

    def quit_app(self):
        self._stop_timer()
        recap = []
        if self.total > 0:
            percentage = 100 * self.score / self.total
            recap.append(
                f"🎮 Conjugation Game: {self.score}/{self.total} ({percentage:.0f}%) "
                f"— best streak {self.best_streak} 🔥"
            )
        if self.total_translation > 0:
            percentage_tr = 100 * self.score_translation / self.total_translation
            recap.append(
                f"🗣️ Translation: {self.score_translation}/{self.total_translation} ({percentage_tr:.0f}%)"
            )
        if recap:
            messagebox.showinfo("Session complete", "\n\n".join(recap))
        self.destroy()

    # ==================================================================
    # PAGE: COURSE
    # ==================================================================

    def _build_course_page(self, parent):
        topbar = tk.Frame(parent, bg=BG_APP)
        topbar.pack(fill="x")
        tk.Button(
            topbar, text="🏠 Menu", font=(FONT_FAMILY, 11, "bold"),
            bg="#D8CDA9", fg=COL_TEXT, relief="flat", bd=0, padx=12, pady=6,
            cursor="hand2", command=self._go_to_menu
        ).pack(side="left", padx=16, pady=10)

        body_container = tk.Frame(parent, bg=BG_APP)
        body_container.pack(fill="both", expand=True)

        canvas = tk.Canvas(body_container, bg=BG_APP, highlightthickness=0)
        scrollbar = ttk.Scrollbar(body_container, orient="vertical", command=canvas.yview)
        inner = tk.Frame(canvas, bg=BG_APP)

        inner.bind("<Configure>", lambda e: canvas.configure(scrollregion=canvas.bbox("all")))
        canvas_window = canvas.create_window((0, 0), window=inner, anchor="n")
        canvas.configure(yscrollcommand=scrollbar.set)

        def _resize_inner(event):
            canvas.coords(canvas_window, event.width / 2, 0)
            canvas.itemconfig(canvas_window, width=min(event.width - 40, 720))
        canvas.bind("<Configure>", _resize_inner)

        def _on_mousewheel(event):
            delta = -1 * (event.delta // 120) if event.delta else (1 if event.num == 5 else -1)
            canvas.yview_scroll(delta, "units")
        canvas.bind("<Enter>", lambda e: (
            canvas.bind_all("<MouseWheel>", _on_mousewheel),
            canvas.bind_all("<Button-4>", _on_mousewheel),
            canvas.bind_all("<Button-5>", _on_mousewheel),
        ))
        canvas.bind("<Leave>", lambda e: (
            canvas.unbind_all("<MouseWheel>"),
            canvas.unbind_all("<Button-4>"),
            canvas.unbind_all("<Button-5>"),
        ))

        canvas.pack(side="left", fill="both", expand=True)
        scrollbar.pack(side="right", fill="y")

        tk.Label(
            inner, text="🍃 🌲 🍃  Course refresher — Spanish conjugation  🍃 🌲 🍃",
            font=(FONT_FAMILY, 19, "bold"), bg=BG_APP, fg=COL_BROWN_DARK, justify="center"
        ).pack(pady=(20, 4))
        tk.Label(
            inner, text="Formation rules, examples, and the most common irregular verbs.",
            font=(FONT_FAMILY, 12, "italic"), bg=BG_APP, fg=COL_MUTED, justify="center"
        ).pack(pady=(0, 16))

        for tense in TENSES:
            self._build_course_section(inner, tense)

        tk.Frame(inner, bg=BG_APP, height=20).pack()

    def _build_course_section(self, parent, tense):
        data = COURSE_DATA[tense]
        color = TENSE_COLORS[tense]
        emoji = TENSE_EMOJI[tense]

        card = tk.Frame(parent, bg=BG_CARD, highlightbackground=color, highlightthickness=3)
        card.pack(pady=(0, 20))

        # Title banner
        banner = tk.Frame(card, bg=color)
        banner.pack(fill="x")
        tk.Label(
            banner, text=f"{emoji} {tense.upper()}", font=(FONT_FAMILY, 20, "bold"),
            bg=color, fg="white", justify="center"
        ).pack(pady=(10, 0))
        tk.Label(
            banner, text=TENSE_SUBTITLES[tense], font=(FONT_FAMILY, 11, "italic"),
            bg=color, fg="white", justify="center"
        ).pack(pady=(0, 10))

        body = tk.Frame(card, bg=BG_CARD)
        body.pack(pady=16, padx=20)

        # Formation rules
        tk.Label(
            body, text="Formation rules (regular verbs)",
            font=(FONT_FAMILY, 14, "bold"), bg=BG_CARD, fg=COL_TEXT, justify="center"
        ).pack(pady=(0, 4))
        tk.Label(
            body, text=data["intro"], font=(FONT_FAMILY, 11), bg=BG_CARD, fg=COL_TEXT,
            wraplength=620, justify="center"
        ).pack(pady=(0, 10))

        self._table_groups(body, data["groups"], color)

        # Examples
        tk.Label(
            body, text="Examples", font=(FONT_FAMILY, 14, "bold"), bg=BG_CARD, fg=COL_TEXT,
            justify="center"
        ).pack(pady=(16, 4))
        for es, en in data["examples"]:
            tk.Label(
                body, text=f"{es}\n{en}", font=(FONT_FAMILY, 11), bg=BG_CARD, fg=COL_TEXT,
                wraplength=620, justify="center"
            ).pack(pady=6)

        # Tip
        tk.Label(
            body, text=data["tip"], font=(FONT_FAMILY, 10, "italic"), bg=BG_CARD, fg=COL_MUTED,
            wraplength=620, justify="center"
        ).pack(pady=(10, 4))

        # Irregular verbs
        tk.Label(
            body, text="Irregular verbs you'll use most",
            font=(FONT_FAMILY, 14, "bold"), bg=BG_CARD, fg=COL_TEXT, justify="center"
        ).pack(pady=(16, 6))

        self._table_irregulars(body, data["irregulars"], color)

        tk.Label(
            body, text=data["irregular_note"], font=(FONT_FAMILY, 10, "italic"),
            bg=BG_CARD, fg=COL_MUTED, wraplength=620, justify="center"
        ).pack(pady=(8, 4))

        # Extra tip (bonus content beyond the original reference sheet)
        tip_box = tk.Frame(body, bg="#F0E6C8", highlightbackground=COL_BROWN, highlightthickness=1)
        tip_box.pack(pady=(12, 4))
        tk.Label(
            tip_box, text=data["extra_tip"], font=(FONT_FAMILY, 10, "bold"),
            bg="#F0E6C8", fg=COL_BROWN_DARK, wraplength=600, justify="center"
        ).pack(padx=10, pady=8)

        # Shortcut button into the game, filtered to this tense
        practice_btn = tk.Button(
            body, text=f"🥾 Practice the {tense} tense ▶", font=(FONT_FAMILY, 11, "bold"),
            bg=color, fg="white", relief="flat", bd=0, padx=14, pady=8, cursor="hand2",
            command=lambda t=tense: self._go_to_game(t)
        )
        practice_btn.pack(pady=(10, 0))

    def _table_groups(self, parent, groups, color):
        table = tk.Frame(parent, bg=BG_CARD)
        table.pack(pady=(0, 4))

        group_names = list(groups.keys())
        tk.Label(
            table, text="", font=(FONT_FAMILY, 10, "bold"), bg=color, fg="white", width=14
        ).grid(row=0, column=0, sticky="nsew", padx=1, pady=1)
        for c, name in enumerate(group_names, start=1):
            tk.Label(
                table, text=name, font=(FONT_FAMILY, 10, "bold"), bg=color, fg="white",
                width=14, padx=4, pady=6
            ).grid(row=0, column=c, sticky="nsew", padx=1, pady=1)

        for r, pronoun in enumerate(PRONOUNS, start=1):
            bg_row = "#EFE7D0" if r % 2 == 0 else BG_CARD
            tk.Label(
                table, text=pronoun, font=(FONT_FAMILY, 10, "bold"), bg=bg_row, fg=COL_TEXT,
                width=14, padx=4, pady=5
            ).grid(row=r, column=0, sticky="nsew", padx=1, pady=1)
            for c, name in enumerate(group_names, start=1):
                form = groups[name][r - 1]
                tk.Label(
                    table, text=form, font=(FONT_FAMILY, 10), bg=bg_row, fg=COL_TEXT,
                    width=14, padx=4, pady=5
                ).grid(row=r, column=c, sticky="nsew", padx=1, pady=1)

    def _table_irregulars(self, parent, irregulars, color):
        table = tk.Frame(parent, bg=BG_CARD)
        table.pack()

        headers = ["Infinitive"] + PRONOUNS
        for c, h in enumerate(headers):
            tk.Label(
                table, text=h, font=(FONT_FAMILY, 9, "bold"), bg=color, fg="white",
                width=12 if c == 0 else 10, padx=3, pady=6
            ).grid(row=0, column=c, sticky="nsew", padx=1, pady=1)

        for r, (infinitive, forms) in enumerate(irregulars, start=1):
            bg_row = "#EFE7D0" if r % 2 == 0 else BG_CARD
            tk.Label(
                table, text=infinitive, font=(FONT_FAMILY, 9, "bold"), bg=bg_row, fg=COL_TEXT,
                width=12, padx=3, pady=4
            ).grid(row=r, column=0, sticky="nsew", padx=1, pady=1)
            for c, form in enumerate(forms, start=1):
                tk.Label(
                    table, text=form, font=(FONT_FAMILY, 9), bg=bg_row, fg=COL_TEXT,
                    width=10, padx=3, pady=4
                ).grid(row=r, column=c, sticky="nsew", padx=1, pady=1)

    # ==================================================================
    # PAGE: TRANSLATION
    # ==================================================================

    def _build_translation_page(self, parent):
        topbar = tk.Frame(parent, bg=BG_APP)
        topbar.pack(fill="x")
        tk.Button(
            topbar, text="🏠 Menu", font=(FONT_FAMILY, 11, "bold"),
            bg="#D8CDA9", fg=COL_TEXT, relief="flat", bd=0, padx=12, pady=6,
            cursor="hand2", command=self._go_to_menu
        ).pack(side="left", padx=16, pady=10)

        header = tk.Frame(parent, bg=TRANSLATION_COLOR, height=110)
        header.pack(fill="x")
        header.pack_propagate(False)
        tk.Label(
            header, text=f"{TRANSLATION_EMOJI} TRANSLATION", font=(FONT_FAMILY, 26, "bold"),
            fg="white", bg=TRANSLATION_COLOR
        ).pack(pady=(20, 0))
        tk.Label(
            header, text="Translate the sentence into Spanish",
            font=(FONT_FAMILY, 12, "italic"), fg="white", bg=TRANSLATION_COLOR
        ).pack()

        # Tense filter (same pattern as the Game tab, but scoped to this page)
        settings = tk.Frame(parent, bg=BG_SETTINGS, highlightbackground=BORDER_SETTINGS, highlightthickness=1)
        settings.pack(fill="x", padx=20, pady=(14, 0))
        row = tk.Frame(settings, bg=BG_SETTINGS)
        row.pack(fill="x", padx=10, pady=10)
        tk.Label(
            row, text="📚 Tense to practice:", font=(FONT_FAMILY, 12, "bold"),
            bg=BG_SETTINGS, fg=COL_BROWN_DARK
        ).pack(side="left", padx=(0, 10))

        self.translation_tense_filter = None
        self.translation_tense_buttons = {}
        tense_choices = [("🔀 All tenses", None)] + [
            (f"{TENSE_EMOJI[t]} {t.capitalize()}", t) for t in TENSES
        ]
        for label, value in tense_choices:
            btn = tk.Button(
                row, text=label, font=(FONT_FAMILY, 11, "bold"),
                relief="flat", bd=0, padx=10, pady=6, cursor="hand2",
                command=lambda v=value: self._set_translation_tense_filter(v)
            )
            btn.pack(side="left", padx=4)
            self.translation_tense_buttons[value] = btn
        self._refresh_translation_tense_buttons()

        # Score
        score_bar = tk.Frame(parent, bg=BG_APP)
        score_bar.pack(fill="x", padx=20, pady=(10, 6))
        self.score_translation_label = tk.Label(
            score_bar, text="🏆 Score: 0/0", font=(FONT_FAMILY, 15, "bold"), bg=BG_APP, fg=COL_TEXT
        )
        self.score_translation_label.pack(side="left")

        # Sentence area
        outer = tk.Frame(parent, bg=BG_APP)
        outer.pack(fill="both", expand=True, padx=20, pady=10)
        self.translation_card = tk.Frame(
            outer, bg=BG_CARD, highlightbackground=TRANSLATION_COLOR, highlightthickness=3
        )
        self.translation_card.pack(fill="both", expand=True)

        self.translation_result_label = tk.Label(
            parent, text="", font=(FONT_FAMILY, 14, "bold"), bg=BG_APP,
            wraplength=760, justify="left"
        )
        self.translation_result_label.pack(fill="x", padx=24, pady=(0, 6))

        # Footer
        footer = tk.Frame(parent, bg=BG_APP)
        footer.pack(fill="x", padx=20, pady=16)
        ttk.Button(
            footer, text="🚪 Quit", style="Quit.TButton", command=self.quit_app
        ).pack(side="left")
        self.translation_submit_btn = ttk.Button(
            footer, text="✅ Submit  (Enter)", style="translation.TButton",
            command=self._on_enter
        )
        self.translation_submit_btn.pack(side="right")

    def _set_translation_tense_filter(self, value):
        self.translation_tense_filter = value
        self._refresh_translation_tense_buttons()

    def _refresh_translation_tense_buttons(self):
        for value, btn in self.translation_tense_buttons.items():
            active = value == self.translation_tense_filter
            color = TENSE_COLORS[value] if value else COL_BROWN_DARK
            if active:
                btn.config(bg=color, fg="white")
            else:
                btn.config(bg="#FFFFFF", fg=COL_BROWN_DARK)

    def new_sentence(self):
        self.translation_reviewing = False
        self.translation_result_label.config(text="")

        self.translation_tense = (
            self.translation_tense_filter if self.translation_tense_filter is not None
            else random.choice(TENSES)
        )
        en, es = random.choice(TRANSLATION_SENTENCES[self.translation_tense])
        self.translation_sentence_en = en
        self.translation_sentence_es = es

        for w in self.translation_card.winfo_children():
            w.destroy()

        tk.Label(
            self.translation_card,
            text=f"{TENSE_EMOJI[self.translation_tense]} Tense requested: {self.translation_tense}",
            font=(FONT_FAMILY, 11, "italic"), bg=BG_CARD, fg=COL_MUTED
        ).pack(pady=(24, 10))

        tk.Label(
            self.translation_card, text=self.translation_sentence_en, font=(FONT_FAMILY, 19, "bold"),
            bg=BG_CARD, fg=COL_TEXT, wraplength=680, justify="center"
        ).pack(pady=(0, 20), padx=20)

        self.translation_entry = ttk.Entry(
            self.translation_card, font=(FONT_FAMILY, 15), width=50, justify="center"
        )
        self.translation_entry.pack(pady=6, ipady=6)
        self.translation_entry.focus_set()

    def _grade_translation(self):
        self.translation_reviewing = True
        self.total_translation += 1

        answer = self.translation_entry.get()
        ok = normalize_sentence(answer) == normalize_sentence(self.translation_sentence_es)
        self.translation_entry.config(state="disabled")

        if ok:
            self.score_translation += 1
            msg = random.choice(CORRECT_MESSAGES)
            self.translation_result_label.config(text=msg, fg=COL_OK)
        else:
            msg = random.choice(WRONG_MESSAGES)
            self.translation_result_label.config(
                text=f"{msg} Expected translation: {self.translation_sentence_es}", fg=COL_KO
            )

        self.score_translation_label.config(
            text=f"🏆 Score: {self.score_translation}/{self.total_translation}"
        )
        self.translation_submit_btn.config(text="▶ Next sentence  (Enter)")


if __name__ == "__main__":
    app = SpanishConjugationApp()
    app.mainloop()
